#!/bin/bash

# Read version from pdxinfo file
version=$(awk -F= '/^version/{print $2}' source/pdxinfo)

# Create zip file with version in the name
zip -r "Weirdling X-$version.zip" "Weirdling X.pdx" -x "*.DS_Store"
